name: teensy_octoWS2811

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '!src/platforms/esp/**'
      - '!src/platforms/wasm/**'
      - '!src/platforms/avr/**'
      - '!src/platforms/arm/rp2040/**'
      - '!src/platforms/arm/sam/**'
      - 'src/platforms/arm/k20/**'
      - 'src/platforms/arm/k66/**'
      - 'src/platforms/arm/kl26/**'
      - 'src/platforms/arm/mxrt1062/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/build_teensy_octo.yml'
      - '.github/workflows/build_template.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'
  pull_request_target:
    branches:
      - master
    paths:
      - 'src/**'
      - '!src/platforms/esp/**'
      - '!src/platforms/wasm/**'
      - '!src/platforms/avr/**'
      - '!src/platforms/arm/rp2040/**'
      - '!src/platforms/arm/sam/**'
      - 'src/platforms/arm/k20/**'
      - 'src/platforms/arm/k66/**'
      - 'src/platforms/arm/kl26/**'
      - 'src/platforms/arm/mxrt1062/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/build_teensy_octo.yml'
      - '.github/workflows/build_template.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'

jobs:
  build:
    uses: ./.github/workflows/build_template.yml
    with:
      args: teensy41 --extra-packages OctoWS2811 --examples SpecialDrivers/Teensy/OctoWS2811/OctoWS2811
