name: ESP32-C3 QEMU Test

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'
      - 'examples/**/*.ino'
      - 'examples/**/*.cpp'
      - 'examples/**/*.h'
      - 'platformio.ini'
      - 'CMakeLists.txt'
      - 'library.json'
      - '.github/workflows/qemu_esp32c3_test.yml'
      - '.github/workflows/qemu_docker_template.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'
      - 'examples/**/*.ino'
      - 'examples/**/*.cpp'
      - 'examples/**/*.h'
      - 'platformio.ini'
      - 'CMakeLists.txt'
      - 'library.json'
      - '.github/workflows/qemu_esp32c3_test.yml'
      - '.github/workflows/qemu_docker_template.yml'

jobs:
  esp32c3_qemu_test:
    strategy:
      fail-fast: false
      matrix:
        sketch: [BlinkParallel, Test]
    uses: ./.github/workflows/qemu_docker_template.yml
    with:
      platform: esp32c3
      platform_display: ESP32-C3
      sketch: ${{ matrix.sketch }}
